version: '3.8'

services:
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=/api
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./content/uploads:/app/public/uploads:delegated
      - ./content/patterns:/app/public/patterns:delegated
      - ./content/fonts:/app/public/fonts:delegated
    environment:
      - DB_HOST=db
      - DB_USER=kopfolio
      - DB_PASSWORD=kopfolio
      - DB_NAME=kopfolio
      - JWT_SECRET=your-secret-key
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=kopfolio
      - POSTGRES_PASSWORD=kopfolio
      - POSTGRES_DB=kopfolio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kopfolio"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf.production:/etc/nginx/conf.d/default.conf
      - ./client/dist:/usr/share/nginx/html
      - ./server/public/uploads:/usr/share/nginx/html/uploads
      - ./content/patterns:/usr/share/nginx/html/patterns
      - ./content/fonts:/usr/share/nginx/html/fonts
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  uploads_data: 